extends: airbnb-base
env:
  browser: true
  jest: true
rules:
  no-underscore-dangle: 0
  no-nested-ternary: 0
  no-bitwise: 0
  no-continue: 0
  no-param-reassign:
  - 2
  - props: false
  valid-jsdoc:
  - 2
  - prefer:
      return: returns
    requireReturnDescription: false
    requireParamDescription: false
  import/extensions:
    - off
    - never
