extends:
  - airbnb-base
  - prettier
env:
  browser: true
  jest: true
globals:
  globalThis: true
rules:
  no-underscore-dangle: 0
  no-nested-ternary: 0
  no-bitwise: 0
  no-continue: 0
  no-prototype-builtins: 1
  no-param-reassign:
  - 2
  - props: false
  valid-jsdoc:
  - 2
  - prefer:
      return: returns
    requireReturnDescription: false
    requireParamDescription: false
