sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - node
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run coverage:report
