#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to Github pages

on:
  push:
    branches:
      - master

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
    - name: Setup
      uses: actions/setup-node@v2-beta
      with:
        node-version: '16.x'
    - name: Install and Build
      run: |
        npm ci
        npm run doc
    - run: touch docs/.nojekyll
    - name: Deploy
      uses: uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs # The folder the action should deploy.